// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSjcKM8_3_aAeJK6ROHkhCUmW_LJ4W3VI',
    appId: '1:196498039196:web:fc9de02bc57ae97fe9a859',
    messagingSenderId: '196498039196',
    projectId: 'uli-dotation',
    authDomain: 'uli-dotation.firebaseapp.com',
    storageBucket: 'uli-dotation.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCphsAjCJzNL2ETFK1tER52u3SzrmnKRAY',
    appId: '1:196498039196:android:eef6a53d34964da3e9a859',
    messagingSenderId: '196498039196',
    projectId: 'uli-dotation',
    storageBucket: 'uli-dotation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfupi863NJ_UZa1tcrXtV58LtGBY25pHs',
    appId: '1:196498039196:ios:10c6a84a853ecf5be9a859',
    messagingSenderId: '196498039196',
    projectId: 'uli-dotation',
    storageBucket: 'uli-dotation.firebasestorage.app',
    iosBundleId: 'com.example.uliDoation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfupi863NJ_UZa1tcrXtV58LtGBY25pHs',
    appId: '1:196498039196:ios:10c6a84a853ecf5be9a859',
    messagingSenderId: '196498039196',
    projectId: 'uli-dotation',
    storageBucket: 'uli-dotation.firebasestorage.app',
    iosBundleId: 'com.example.uliDoation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSjcKM8_3_aAeJK6ROHkhCUmW_LJ4W3VI',
    appId: '1:196498039196:web:3ceb2eba64e1f965e9a859',
    messagingSenderId: '196498039196',
    projectId: 'uli-dotation',
    authDomain: 'uli-dotation.firebaseapp.com',
    storageBucket: 'uli-dotation.firebasestorage.app',
  );
}
